#server:
#  port: 8081
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: false
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  type-aliases-package: com.longlive.kmong.DTO
  mapper-locations:
    classpath:mybatis/*.xml

spring:
   resources:
    static-locations: file:/Users/윤민수/Downloads/kmongimage/
   servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


   datasource:
#     url: jdbc:mysql://127.0.0.1:3306/new?useUnicode=true&serverTimezone=Asia/Seoul
     url: jdbc:mysql://talentmarket-springboot-webservice.cmnyyxiclarl.ap-northeast-2.rds.amazonaws.com:3306/talentmarket_springboot_webservice?useUnicode=true&serverTimezone=Asia/Seoul
#     username: root
#     password: u1234
     username: talentmarket
     password: 2938145a
     redis:
       lettuce:
         pool:
           max-active: 10
           max-idle: 10
           min-idle: 2
       port: 6379
       host: 127.0.0.1
       password: 'foobared'

   thymeleaf:
     prefix: classpath:templates/
     suffix: .html
     cache: false
     encoding: UTF-8

   security:
      oauth2:
        client:
          registration:
           google:
            client-id: 566151186767-k6a9rlhmmnsv79fgjavcq0nbtg9to5bm.apps.googleusercontent.com
            client-secret: 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
            scope: email,profile
           kakao:
            client-id: 2ff1123942d1ede953a97b2a4eb8ca3a
            client-secret: zVPBMSLJknNjvEqalESywxZvyahItYJ7
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
                 - profile_nickname
                 - account_email


           naver:
            client-id: wViGT9VINjbT6DEXW8Mb
            client-secret: rq45Vd09qB
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver



          provider:
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id

              #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.
